### ISSUE TITLE
Reproduction Error

### ISSUE THREAD

**Issue by BiEchi** [shuoyangd/tarsius#1]
Excuse me, I think the model weights are deprecated.

```
Traceback (most recent call last):
  File "/home/ubuntu/tarsius/fairseq/compute_salience_fairseq_set.py", line 323, in <module>
    cli_main()
  File "/home/ubuntu/tarsius/fairseq/compute_salience_fairseq_set.py", line 319, in cli_main
    main(args)
  File "/home/ubuntu/tarsius/fairseq/compute_salience_fairseq_set.py", line 306, in main
    frac = evaluate(prefix_data, tag_data, subjs_data, attrs_data, model, parsed_args.output, parsed_args.cuda, parsed_args.sequential)
  File "/home/ubuntu/tarsius/fairseq/compute_salience_fairseq_set.py", line 108, in evaluate
    no_salience_output, _ = model(prefix_batch.transpose(0, 1), None)  # (batch_size, padded_seq_len, vocab_size)
  File "/opt/conda/envs/pytorch/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ubuntu/tarsius/fairseq/fairseq/models/fairseq_model.py", line 287, in forward
    return self.decoder(src_tokens)
  File "/opt/conda/envs/pytorch/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ubuntu/tarsius/fairseq/fairseq/models/transformer.py", line 527, in forward
    x, attn = layer(
  File "/opt/conda/envs/pytorch/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ubuntu/tarsius/fairseq/fairseq/models/transformer.py", line 733, in forward
    x, _ = self.self_attn(
  File "/opt/conda/envs/pytorch/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ubuntu/tarsius/fairseq/fairseq/modules/multihead_attention.py", line 109, in forward
    q *= self.scaling
RuntimeError: Output 0 of SplitBackward0 is a view and is being modified inplace. This view is the output of a function that returns multiple views. Such functions do not allow the output views to be modified inplace. You should replace the inplace operation by an out-of-place one.
```

Is it possible for you to train a new version? Many thanks for any help!

**Comment by shuoyangd** [comment]
I'll need more context to understand what the exact problem is. What PyTorch version are you using?

I don't think this is a matter of deprecated model weights. A quick search pointed me to [this](https://github.com/pytorch/vision/issues/3025).

**Comment by BiEchi** [comment]
I'm currently using Python 3.9.16 with PyTorch 1.13.1 and HF 4.29.2.
It would be very helpful for us if you can provide the environment you developed.
I looked into the issue you pointed to - in our case, the problem happens in the line `no_salience_output, _ = model(prefix_batch.transpose(0, 1), None)`, so it's probably a problem with fairseq or torch. So given the version of the env the issue might be addressed.

**Comment by shuoyangd** [comment]
Those were run with Python 3.6.1, PyTorch 1.2, and CUDA 9.2 -- quite ancient setup from today's perspective. I pointed to the exact fairseq commit I used to run my experiments, so that's not the source of the problem.

If you can set up that kind of environment, give it a shot, since I think this is most likely a torch problem. Otherwise, I can attempt to come up with a quick fix to make it runnable under a modern setup, but no guarantees.

**Comment by BiEchi** [comment]
Yup it's the torch issue. Now it successfully runs. Is this the expected behavior?
```
2023-06-09 03:40:38 INFO: running frac: 87 / 169 = 0.514792899408284
2023-06-09 03:40:38 INFO: running pos frac: 78 / 154 = 0.5064935064935064
2023-06-09 03:40:38 INFO: running neg frac: 9 / 15 = 0.6
2023-06-09 03:40:38 INFO: running frac: 87 / 170 = 0.5117647058823529
2023-06-09 03:40:38 INFO: running pos frac: 78 / 155 = 0.5032258064516129
2023-06-09 03:40:38 INFO: running neg frac: 9 / 15 = 0.6
2023-06-09 03:40:38 INFO: running frac: 87 / 171 = 0.5087719298245614
2023-06-09 03:40:38 INFO: running pos frac: 78 / 156 = 0.5
2023-06-09 03:40:38 INFO: running neg frac: 9 / 15 = 0.6
2023-06-09 03:40:39 INFO: running frac: 87 / 172 = 0.5058139534883721
2023-06-09 03:40:39 INFO: running pos frac: 78 / 157 = 0.4968152866242038
2023-06-09 03:40:39 INFO: running neg frac: 9 / 15 = 0.6
2023-06-09 03:40:39 INFO: running frac: 87 / 173 = 0.5028901734104047
2023-06-09 03:40:39 INFO: running pos frac: 78 / 158 = 0.4936708860759494
2023-06-09 03:40:39 INFO: running neg frac: 9 / 15 = 0.6
2023-06-09 03:40:39 INFO: running frac: 87 / 174 = 0.5
2023-06-09 03:40:39 INFO: running pos frac: 78 / 159 = 0.49056603773584906
2023-06-09 03:40:39 INFO: running neg frac: 9 / 15 = 0.6
2023-06-09 03:40:40 INFO: running frac: 88 / 175 = 0.5028571428571429
2023-06-09 03:40:40 INFO: running pos frac: 78 / 159 = 0.49056603773584906
2023-06-09 03:40:40 INFO: running neg frac: 10 / 16 = 0.625
```

**Comment by shuoyangd** [comment]
Good to know! Definitely not "expected", but I didn't know what to expect for PyTorch 1.13 back in 2020 :)

**Comment by BiEchi** [comment]
;) that's interesting. Thanks for solving this issue! I'm closing it as we've tackled it.
